name: 'Aliyun Serverless Initialization Github Actions'
description: 'Install Aliyun Serverless tool and configure the credentials'

inputs:
  provider:
    description: 'The cloud service provider. [alibaba/aws/azure/baidu/google/huawei/tencent]'
    required: false
    default: "alibaba"
  access_key_id:
    description: 'Configure the access_key_id'
    required: true
  access_key_secret:
    description: 'Configure the access_key_secret'
    required: true
  account_id:
    description: 'Configure the account_id'
    required: true

branding:
  icon: 'cloud-lightning'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Setup node12
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install Serverless-Devs
      run: npm install -g @serverless-devs/s
      shell: bash
    - name: Configure Serverless-Devs
      run: $GITHUB_ACTION_PATH/dev/config.sh
      shell: bash