name: 'Serverless-Devs Initialization Github Actions'
description: 'Install Serverless-Devs tool and configure the credentials'

inputs:
  provider:
    description: 'The cloud service provider. [alibaba/aws/azure/baidu/google/huawei/tencent]'
    required: true
  AccountID:
    description: 'Configure the AccountID'
    required: false
  AccessKeyID:
    description: 'Configure the AccessKeyID'
    required: false
  AccessKeySecret:
    description: 'Configure the AccessKeySecret'
    required: false
  SecretID:
    description: 'Configure the SecretID'
    required: false
  SecretKey:
    description: 'Configure the SecretKey'
    required: false
  SecretAccessKey:
    description: 'Configure the SecretAccessKey'
    required: false
  KeyVaultName:
    description: 'Configure the KeyVaultName'
    required: false
  TenantID:
    description: 'Configure the TenantID'
    required: false
  ClientID:
    description: 'Configure the ClientID'
    required: false
  ClientSecret:
    description: 'Configure the ClientSecret'
    required: false
  PrivateKeyData:
    description: 'Configure the PrivateKeyData'
    required: false

branding:
  icon: 'cloud-lightning'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Install Serverless-Devs
      run: sudo npm install -g @serverless-devs/s
      shell: bash
    - name: Configure Serverless-Devs
      run: ${{ github.action_path }}/dev/config.sh
      shell: bash
      env:
        INPUT_PROVIDER: ${{ inputs.provider }}
        INPUT_ACCOUNT_ID: ${{ inputs.AccountID }}
        INPUT_ACCESS_KEY_ID: ${{ inputs.AccessKeyID }}
        INPUT_ACCESS_KEY_SECRET: ${{ inputs.AccessKeySecret }}
        INPUT_SECRET_ID: ${{ inputs.SecretID }}
        INPUT_SECRET_KEY: ${{ inputs.SecretKey }}
        INPUT_SECRET_ACCESS_KEY: ${{ inputs.SecretAccessKey }}
        INPUT_KEY_VAULT_NAME: ${{ inputs.KeyVaultName }}
        INPUT_TENANT_ID: ${{ inputs.TenantID }}
        INPUT_CLIENT_ID: ${{ inputs.ClientID }}
        INPUT_CLIENT_SECRET: ${{ inputs.ClientSecret }}
        INPUT_PRIVATE_KEY_DATA: ${{ inputs.PrivateKeyData }}
