name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Test config.sh
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Initializing Serverless-Devs with alibaba
      uses: ./
      with: 
        provider: alibaba
        account_id: ${{ secrets.ALIYUN_ACCOUNT_ID }}
        access_key_id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        access_key_secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
    - name: Check version and configuration
      run: |
        sudo s --version
        sudo s config get -l