name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Test config.sh
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Serverless-Devs
      run: sudo npm install -g @serverless-devs/s
      shell: bash
    - name: Run config.sh
      run: sudo bash ./dev/config.sh
      env:
        INPUT_ACCOUNT_ID: ${{ secrets.ALIYUN_ACCOUNT_ID }}
        INPUT_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        INPUT_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        INPUT_PROVIDER: alibaba